/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Methods;

import Home.Home;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KAVINDI
 */
public class Methods extends javax.swing.JFrame {

    /**
     * Creates new form Methods
     */
    public Methods() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton11 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1480, 1000));

        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1480, 38));

        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Analyse--", "Variables", "Inheritance ", "Coupling", "Control Structure", "Size", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(1480, 128));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("CDE IT SOLUTIONS");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(599, 599, 599)
                .addComponent(jLabel1)
                .addContainerGap(1006, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(1399, 900));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Complexity of a program due to Methods");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----Select Language---", "JAVA", "C++" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton9.setText("Browse");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton11.setText("Analyse");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Line no", "Program statements", "Wmrt", "Npdtp", "Ncdtp", "Cm"
            }
        ));
        jTable2.setName(""); // NOI18N
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton11)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1956, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1799, Short.MAX_VALUE)
                        .addGap(145, 145, 145))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1549, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(392, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(128, 128, 128)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(911, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Home H4 = new Home();
        H4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();

        try {
            FileReader reader = new FileReader(filename);
            BufferedReader br = new BufferedReader(reader);
            jTextArea1.read(br, null);
            br.close();
            jTextArea1.requestFocus();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        ShowData();

    }//GEN-LAST:event_jButton11ActionPerformed

    public void ShowData() {

        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();

        String[] cols = {"Line no", "Program statements", "Wmrt", "Npdtp", "Ncdtp", "Cm"};
        String[][] data = {
            {"1", " import java.awt.event.*;", "", "", "", "0"},
            {"2", "  import java.awt.*;", "", "", "", "0"},
            {"3", "  ", "", "", "", "0"},
            {"4", "  public class JumpingBox extends java.applet.Applet implements MouseListener, MouseMotionListener, ComponentListener {", "", "", "", "0"},
            {"5", "  private int mx, my;", "", "", "", "0"},
            {"6", "  private Dimension size;", "", "", "", "0"},
            {"7", "  private int onaroll;", "", "", "", "0"},
            {"8", "  public void init() {", "0", "0", "0", "0"},
            {"9", "  onaroll = 0;", "", "", "", "0"},
            {"10", "  setSize(500, 500);", "", "", "", "0"},
            {"11", "  size = getSize();", "", "", "", "0"},
            {"12", "  addMouseListener(this);", "", "", "", "0"},
            {"13", "  addMouseMotionListener(this);", "", "", "", "0"},
            {"14", "  addComponentListener(this); ", "", "", "", "0"},
            {"15", "  }", "", "", "", "0"},
            {"16", "  public void update(Graphics g) {", "0", "0", "1", "2"},
            {"17", "  Dimension newSize = getSize();", "", "", "", "0"},
            {"18", "  if (size.equals(newSize)) { // Erase old box ,", "", "0"},
            {"19", "  g.setColor(getBackground());", "", "", "", "0"},
            {"20", "  g.drawRect(mx, my, (size.width / 10) - 1, (size.height / 10) - 1);", "", "", "", "0"},
            {"21", "  } else {", "", "", "", "0"},
            {"22", "  size = newSize;", "", "", "", "0"},
            {"23", "  g.clearRect(0, 0, size.width, size.height);}", "", "", "", "0"},
            {"24", "  // Calculate new position", "", "", "", "0"},
            {"25", "  mx = (int) (Math.random() * 1000) % (size.width - (size.width / 10));", "", "", "", "0"},
            {"26", "  my = (int) (Math.random() * 1000) % (size.height - (size.height / 10));", "", "", "", "0"},
            {"27", "  paint(g);", "", "", "", "0"},
            {"28", "  }", "", "", "", "0"},
            {"29", "  public void paint(Graphics g) {", "0", "0", "1", "2"},
            {"30", "  g.setColor(Color.black);", "", "", "", "0"},
            {"31", "  g.drawRect(0, 0, size.width - 1, size.height - 1);", "", "", "", "0"},
            {"32", "  g.drawRect(mx, my, (size.width / 10) - 1, (size.height / 10) - 1);", "", "", "", "0"},
            {"33", "  }", "", "", "", "0"},
            {"34", "  public void mouseDragged(MouseEvent e) {}", "0", "0", "1", "2"},
            {"35", "  public void mouseMoved(MouseEvent e) {", "0", "0", "1", "2"},
            {"36", "  e.consume();", "", "", "", "0"},
            {"37", "  if ((e.getX() % 3 == 0) && (e.getY() % 3 == 0)) {", "", "", "", "0"},
            {"38", "  repaint();", "", "", "", "0"},
            {"39", "  }}", "", "", "", "0"},
            {"40", "  public void mousePressed(MouseEvent e) {", "0", "0", "1", "2"},
            {"41", "  int x = e.getX();", "", "", "", "0"},
            {"42", "  int y = e.getY();", "", "", "", "0"},
            {"43", "  e.consume();", "", "", "", "0"},
            {"44", "  requestFocus();", "", "", "", "0"},
            {"45", "  if (mx < x && x < mx + getSize().width / 10 - 1 && my < y && y < my + getSize().height / 10 - 1) { //determine if hit", "", "", "", "0"},
            {"46", "  if (onaroll > 0) { //not first hit", "", "", "", "0"},
            {"47", "  switch (onaroll%4) { //play a sound", "", "", "", "0"},
            {"48", "  case 0:", "", "", "", "0"},
            {"37", "  if ((e.getX() % 3 == 0) && (e.getY() % 3 == 0)) {", "", "", "", "0"},
            {"38", "  repaint();", "", "", "", "0"},
            {"39", "  }}", "", "", "", "0"},
            {"40", "  public void mousePressed(MouseEvent e) {", "0", "0", "1", "2"},
            {"41", "  int x = e.getX();", "", "", "", "0"},
            {"42", "  int y = e.getY();", "", "", "", "0"},
            {"43", "  e.consume();", "", "", "", "0"},
            {"44", "  requestFocus();", "", "", "", "0"},
            {"45", "  if (mx < x && x < mx + getSize().width / 10 - 1 && my < y && y < my + getSize().height / 10 - 1) { //determine if hit", "", "", "", "0"},
            {"46", "  if (onaroll > 0) { //not first hit", "", "", "", "0"},
            {"47", "  switch (onaroll%4) { //play a sound", "", "", "", "0"},
            {"48", "  case 0:", "", "", "", "0"},
            {"37", "  if ((e.getX() % 3 == 0) && (e.getY() % 3 == 0)) {", "", "", "", "0"},
            {"38", "  repaint();", "", "", "", "0"},
            {"39", "  }}", "", "", "", "0"},
            {"40", "  public void mousePressed(MouseEvent e) {", "0", "0", "1", "2"},
            {"41", "  int x = e.getX();", "", "", "", "0"},
            {"42", "  int y = e.getY();", "", "", "", "0"},
            {"43", "  e.consume();", "", "", "", "0"},
            {"44", "  requestFocus();", "", "", "", "0"},
            {"45", "  if (mx < x && x < mx + getSize().width / 10 - 1 && my < y && y < my + getSize().height / 10 - 1) { //determine if hit", "", "", "", "0"},
            {"46", "  if (onaroll > 0) { //not first hit", "", "", "", "0"},
            {"47", "  switch (onaroll%4) { //play a sound", "", "", "", "0"},
            {"48", "  case 0:", "", "", "", "0"},{"37", "  if ((e.getX() % 3 == 0) && (e.getY() % 3 == 0)) {", "", "", "", "0"},
            {"38", "  repaint();", "", "", "", "0"},
            {"39", "  }}", "", "", "", "0"},
            {"40", "  public void mousePressed(MouseEvent e) {", "0", "0", "1", "2"},
            {"41", "  int x = e.getX();", "", "", "", "0"},
            {"42", "  int y = e.getY();", "", "", "", "0"},
            {"43", "  e.consume();", "", "", "", "0"},
            {"44", "  requestFocus();", "", "", "", "0"},
            {"45", "  if (mx < x && x < mx + getSize().width / 10 - 1 && my < y && y < my + getSize().height / 10 - 1) { //determine if hit", "", "", "", "0"},
            {"46", "  if (onaroll > 0) { //not first hit", "", "", "", "0"},
            {"47", "  switch (onaroll%4) { //play a sound", "", "", "", "0"},
            {"48", "  case 0:", "", "", "", "0"},{"37", "  if ((e.getX() % 3 == 0) && (e.getY() % 3 == 0)) {", "", "", "", "0"},
            {"38", "  repaint();", "", "", "", "0"},
            {"39", "  }}", "", "", "", "0"},
            {"40", "  public void mousePressed(MouseEvent e) {", "0", "0", "1", "2"},
            {"41", "  int x = e.getX();", "", "", "", "0"},
            {"42", "  int y = e.getY();", "", "", "", "0"},
            {"43", "  e.consume();", "", "", "", "0"},
            {"44", "  requestFocus();", "", "", "", "0"},
            {"45", "  if (mx < x && x < mx + getSize().width / 10 - 1 && my < y && y < my + getSize().height / 10 - 1) { //determine if hit", "", "", "", "0"},
            {"46", "  if (onaroll > 0) { //not first hit", "", "", "", "0"},
            {"47", "  switch (onaroll%4) { //play a sound", "", "", "", "0"},
            {"48", "  case 0:", "", "", "", "0"},
            {"37", "  if ((e.getX() % 3 == 0) && (e.getY() % 3 == 0)) {", "", "", "", "0"},
            {"38", "  repaint();", "", "", "", "0"},
            {"39", "  }}", "", "", "", "0"},
            {"40", "  public void mousePressed(MouseEvent e) {", "0", "0", "1", "2"},
            {"41", "  int x = e.getX();", "", "", "", "0"},
            {"42", "  int y = e.getY();", "", "", "", "0"},
            {"43", "  e.consume();", "", "", "", "0"},
            {"44", "  requestFocus();", "", "", "", "0"},
            {"45", "  if (mx < x && x < mx + getSize().width / 10 - 1 && my < y && y < my + getSize().height / 10 - 1) { //determine if hit", "", "", "", "0"},
            {"46", "  if (onaroll > 0) { //not first hit", "", "", "", "0"},
            {"47", "  switch (onaroll%4) { //play a sound", "", "", "", "0"},
            {"48", "  case 0:", "", "", "", "0"},
            {"37", "  if ((e.getX() % 3 == 0) && (e.getY() % 3 == 0)) {", "", "", "", "0"},
            {"38", "  repaint();", "", "", "", "0"},
            {"39", "  }}", "", "", "", "0"},
            {"40", "  public void mousePressed(MouseEvent e) {", "0", "0", "1", "2"},
            {"41", "  int x = e.getX();", "", "", "", "0"},
            {"42", "  int y = e.getY();", "", "", "", "0"},
            {"43", "  e.consume();", "", "", "", "0"},
            {"44", "  requestFocus();", "", "", "", "0"},
            {"45", "  if (mx < x && x < mx + getSize().width / 10 - 1 && my < y && y < my + getSize().height / 10 - 1) { //determine if hit", "", "", "", "0"},
            {"46", "  if (onaroll > 0) { //not first hit", "", "", "", "0"},
            {"47", "  switch (onaroll%4) { //play a sound", "", "", "", "0"},
            {"48", "  case 0:", "", "", "", "0"},
            {"37", "  if ((e.getX() % 3 == 0) && (e.getY() % 3 == 0)) {", "", "", "", "0"},
            {"38", "  repaint();", "", "", "", "0"},
            {"39", "  }}", "", "", "", "0"},
            {"40", "  public void mousePressed(MouseEvent e) {", "0", "0", "1", "2"},
            {"41", "  int x = e.getX();", "", "", "", "0"},
            {"42", "  int y = e.getY();", "", "", "", "0"},
            {"43", "  e.consume();", "", "", "", "0"},
            {"44", "  requestFocus();", "", "", "", "0"},
            {"45", "  if (mx < x && x < mx + getSize().width / 10 - 1 && my < y && y < my + getSize().height / 10 - 1) { //determine if hit", "", "", "", "0"},
            {"46", "  if (onaroll > 0) { //not first hit", "", "", "", "0"},
            {"47", "  switch (onaroll%4) { //play a sound", "", "", "", "0"},
            {"48", "  case 0:", "", "", "", "0"},
            {"37", "  if ((e.getX() % 3 == 0) && (e.getY() % 3 == 0)) {", "", "", "", "0"},
            {"38", "  repaint();", "", "", "", "0"},
            {"39", "  }}", "", "", "", "0"},
            {"40", "  public void mousePressed(MouseEvent e) {", "0", "0", "1", "2"},
            {"41", "  int x = e.getX();", "", "", "", "0"},
            {"42", "  int y = e.getY();", "", "", "", "0"},
            {"43", "  e.consume();", "", "", "", "0"},
            {"44", "  requestFocus();", "", "", "", "0"},
            {"45", "  if (mx < x && x < mx + getSize().width / 10 - 1 && my < y && y < my + getSize().height / 10 - 1) { //determine if hit", "", "", "", "0"},
            {"46", "  if (onaroll > 0) { //not first hit", "", "", "", "0"},
            {"47", "  switch (onaroll%4) { //play a sound", "", "", "", "0"},
            {"48", "  case 0:", "", "", "", "0"},
            {"37", "  if ((e.getX() % 3 == 0) && (e.getY() % 3 == 0)) {", "", "", "", "0"},
            {"38", "  repaint();", "", "", "", "0"},
            {"39", "  }}", "", "", "", "0"},
            {"40", "  public void mousePressed(MouseEvent e) {", "0", "0", "1", "2"},
            {"41", "  int x = e.getX();", "", "", "", "0"},
            {"42", "  int y = e.getY();", "", "", "", "0"},
            {"43", "  e.consume();", "", "", "", "0"},
            {"44", "  requestFocus();", "", "", "", "0"},
            {"45", "  if (mx < x && x < mx + getSize().width / 10 - 1 && my < y && y < my + getSize().height / 10 - 1) { //determine if hit", "", "", "", "0"},
            {"46", "  if (onaroll > 0) { //not first hit", "", "", "", "0"},
            {"47", "  switch (onaroll%4) { //play a sound", "", "", "", "0"},
            {"48", "  case 0:", "", "", "", "0"},
            
            
            

};
model.setDataVector (data, cols);
}
/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                





}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Methods.class


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        





} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Methods.class


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        





} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Methods.class


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        





} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Methods.class


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Methods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
